-- Run this once in the Supabase SQL editor.
create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  names text not null check (char_length(names) between 2 and 200),
  created_at timestamptz not null default now()
);

alter table public.rsvps enable row level security;

-- Visitors can confirm attendance, but cannot read or change other responses.
drop policy if exists "Anyone can submit an RSVP" on public.rsvps;

create policy "Anyone can submit an RSVP"
on public.rsvps
for insert
to anon
with check (char_length(names) between 2 and 200);

revoke all on table public.rsvps from anon;
grant insert on table public.rsvps to anon;
grant usage, select on sequence public.rsvps_id_seq to anon;
